### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by MayMeow** [CakeSource/simple-server#1]
Readme file wanted :) 👍

**Comment by iashris** [comment]
I could do it :)

**Comment by iashris** [comment]
Ah gone with the wind.

**Comment by Xenira** [comment]
@iashris Sorry :/

**Comment by seth10** [comment]
Lol I was just writing one too. Found this issue from a Hacktoberfest search?

**Comment by Xenira** [comment]
@seth10 Yea, should be my second pull request. 2 to go :)

**Comment by seth10** [comment]
@Xenira In case you didn't know, you can check it! https://hacktoberfestchecker.herokuapp.com
